### ISSUE TITLE
ruimarinho/bitcoin-core:0.18-alpine non working at all

### ISSUE THREAD

**Issue by yshurik** [ruimarinho/docker-bitcoin-core#100]
latest update of image ruimarinho/bitcoin-core:0.18-alpine and:

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: event_base_once: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: bufferevent_get_output: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: evhttp_request_get_command: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: bufferevent_disable: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZN5boost10filesystem6detail18create_directoriesERKNS0_4pathEPNS_6system10error_codeE: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: evhttp_send_error: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: evhttp_request_get_output_buffer: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZN5boost10filesystem6detail10equivalentERKNS0_4pathES4_PNS_6system10error_codeE: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZN5boost6chrono12system_clock3nowEv: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZN5boost6system16generic_categoryEv: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZTIN5boost6detail16thread_data_baseE: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZTIN5boost6detail16thread_data_baseE: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZTIN5boost6detail16thread_data_baseE: symbol not found

Error relocating /opt/bitcoin-0.18.1/bin/bitcoind: _ZTVN5boost6detail16thread_data_baseE: symbol not found

Why not test before push image to hub?

**Comment by ruimarinho** [comment]
Indeed, there was an issue with runtime libraries. When porting over the travis build scripts, the runtime time test went missing.

Fixed on https://github.com/ruimarinho/docker-bitcoin-core/commit/5b41173b4d495113c3e4650a9a494b99c2a99f66.

**Comment by yshurik** [comment]
If you add just RUN bitcoind --help to the dockerfile so it is always an indication that it is at least runnable

**Comment by ruimarinho** [comment]
Yep. I'm doing something similar with https://github.com/ruimarinho/docker-bitcoin-core/blob/master/.github/workflows/build.yaml#L133-L137, but the RUN command might be better.
