### ISSUE TITLE
Docker hub still shows 0.20.0

### ISSUE THREAD

**Issue by dmp1ce** [ruimarinho/docker-bitcoin-core#103]
Docker hub still shows `0.20.0` in the README as a tag. Although I assume it is `0.20.1` now or just `0.20`.

https://hub.docker.com/r/ruimarinho/bitcoin-core

I also couldn't search for `0.20.1` tag on docker hub.

**Comment by ruimarinho** [comment]
I'm making some improvements to the automated GitHub Actions workflow so it got a bit delayed. Sorry about that, it is there now!
