### ISSUE TITLE
Bitcoin Core 0.21

### ISSUE THREAD

**Issue by schildbach** [ruimarinho/docker-bitcoin-core#107]
0.21.0 has been released. It would be nice to have this option in these docker images.

**Comment by nicolasburtey** [comment]
a PR has been created already: https://github.com/ruimarinho/docker-bitcoin-core/pull/106

not sure if this repo is still maintained

**Comment by schildbach** [comment]
The weird thing is that the other Docker image was several versions behind a couple of months ago, so I assumed that the other image wasn't maintained any more and I switched to this one.

**Comment by torkelrogstad** [comment]
This repo is still maintained, and a 0.21 image is coming out. The maintainer has other things in his life to care to as well, which I think we should respect. 

In the meantime, I'd suggest copying the Dockerfile from this repo, and building it yourself.

**Comment by ruimarinho** [comment]
Landed in https://github.com/ruimarinho/docker-bitcoin-core/commit/e1455ce7d6f9f2842061b980d9c516b9a6d19dae thanks to @torkelrogstad.

Appreciate all the support. Images are being built by GitHub Actions as we speak.

**Comment by schildbach** [comment]
Thanks a lot for updating this.
