### ISSUE TITLE
Problem during compile when running 0.2.0 Alpine Dockerfile

### ISSUE THREAD

**Issue by jeroenvanagt** [ruimarinho/docker-bitcoin-core#110]
Hi,

I just tried to use the Dockerfile for 0.2.0 for Alpine.
Everything seems to go Ok until RUN make -j4 is run, it returns the following error:

`Step 47/69 : RUN make -j4
 ---> Running in d234fab5d656
Making all in src
make[1]: Entering directory '/bitcoin-0.20.1/src'
make[2]: Entering directory '/bitcoin-0.20.1/src'
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-banman.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-blockfilter.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-flatfile.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-net_processing.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [Makefile:10646: libbitcoin_server_a-init.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/bitcoin-0.20.1/src'
make[1]: *** [Makefile:17263: all-recursive] Error 1
make[1]: Leaving directory '/bitcoin-0.20.1/src'
make: *** [Makefile:781: all-recursive] Error 1
ERROR: Service 'bitcoin' failed to build : The command '/bin/sh -c make -j4' returned a non-zero code: 2`

Does this problem sounds familiar?

**Comment by ruimarinho** [comment]
I'm inclined to say you're simply running out of memory. I'm assuming you mean 0.20.0. Jobs appear to be working fine for alpine (https://github.com/ruimarinho/docker-bitcoin-core/runs/1854385295?check_suite_focus=true).
