### ISSUE TITLE
RPC won't bind on minimal docker-compose example

### ISSUE THREAD

**Issue by keblek** [ruimarinho/docker-bitcoin-core#115]
```version: "3.3"
services:
  bitcoind:
    container_name: bitcoind
    image: ruimarinho/bitcoin-core:latest
    command:
     -signet=1
     -server=1
```

I keep getting the following error,

`Binding RPC on address ::1 port 38332 failed.`

I would really appreciate some help for how to get the RPC port to work since I am trying to connect a lightning node to it. I was thinking once I learn how to do this I could add it to the readme.

**Comment by ruimarinho** [comment]
Docker IPv6 is only supported on Linux hosts and I believe you need to manually enable it.

Try binding to IPv4 allow:

```
-rpcbind=127.0.0.1
-rpcallowip=0.0.0.0/0
```
