### ISSUE TITLE
Consider switching the download links to https://bitcoincore.org

### ISSUE THREAD

**Issue by schildbach** [ruimarinho/docker-bitcoin-core#118]
https://bitcoin.org/ seems slow to update. I can try to provide a PR if @ruimarinho agrees with such switch.

**Comment by ruimarinho** [comment]
Yes. I can see that's an official domain. https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/contrib/verifybinaries/verify.py#L24-L25

**Comment by schildbach** [comment]
Thanks!
