### ISSUE TITLE
0.21 unable to restart

### ISSUE THREAD

**Issue by prunelsigma** [ruimarinho/docker-bitcoin-core#119]
Hi,
First, thank you for your work. :)
It seems you updated the `0.21` tag some days ago since this update, my node using the docker `0.21` is unable to restart.
I'm getting this error in the logs (this is the entire logs):
```
Error: Failed saving settings file:
- Error: Unable to open settings file /data/settings.json.tmp for writing
```
I'm not sure what this error is about:
- data corruption?
- bitcoind build ? (a quick google lookup seems to point at bitcoin-qt build).

If you have an idea ? Thank you in advance.

**Comment by prunelsigma** [comment]
after some investigation, it seems the error is about data corruption.
It seems my node restarting and your update was really bad timing causing this problem.

For anyone with the same problem:
I'm afraid you need to restart from scratch (or snapshot in my case) since `-reindex-chainstate` will not even start.
Maybe deleting a specific file will solve this better, I'm not sure which corrupted file is causing this.

**Comment by ruimarinho** [comment]
@prunelsigma my recommendation is to use specific version tags to avoid any issues like that. Glad you were to at least find the problem.
