### ISSUE TITLE
Best way to upgrade image and not resync chain

### ISSUE THREAD

**Issue by Bit-Shifts** [ruimarinho/docker-bitcoin-core#122]
Is it possible to use docker compose to update image and not have to create a new volume and sync all over again?

**Comment by ruimarinho** [comment]
Sure, you would just update the image hash and ensure the blockchain data is mounted on a volume (either through a bind-mount or a docker volume).

**Comment by Bit-Shifts** [comment]
Ok. it appears to just be mounting to a dynamic volume now. 

would 'docker-compose -f docker-compose.testnet.yml up -d' simply recreate the container with the new image and keep the existing volume?

**Comment by ruimarinho** [comment]
Yes, as long as the bind-mount or the docker volumes are declared on the docker-compose.yaml file, thus not being ephemeral.
