### ISSUE TITLE
`chmod` and exfat drives

### ISSUE THREAD

**Issue by ManuelSchneid3r** [ruimarinho/docker-bitcoin-core#130]
Changing permissions on exfat drives is not allowed. The entrypoint script fails.

`bitcoin           | chown: changing ownership of '/home/bitcoin/.bitcoin': Operation not permitted`

Why exactly are those two lines needed?

https://github.com/ruimarinho/docker-bitcoin-core/blob/master/23/docker-entrypoint.sh#L12-L13

**Comment by Husseinat** [comment]
Is there any workarounds for this so far?

**Comment by ruimarinho** [comment]
Those lines are there to ensure good security practices: only the bitcoin user can read, write and execute files contained in it.

However, the entrypoint is completely optional. It's there as a helper. You have two workarounds:

1. Switching filesystems. Exfat does not support storing the bits required to hold permission data. I suppose this is not practical for you.
2. Replacing the entrypoint but a direct call to `bitcoind`. An example command ignoring the bundled entrypoint:

    ```
    docker run --rm -it --entrypoint bitcoind ruimarinho/bitcoin-core:24 -version
    ```

Hope this helps!
