### ISSUE TITLE
Add support for Bitcoin Core v24.0 release candidates

### ISSUE THREAD

**Issue by msgilligan** [ruimarinho/docker-bitcoin-core#131]
There are release candidate binary releases of Bitcoin Core v24.0 available now and a [Testing Guide: Bitcoin Core 24.0 Release Candidate](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide) document.

I would be great to be able to do testing using this Docker container. Is anyone else interested in getting a start on a v24.0 RC version of this container? If I put together a PR is there interested in reviewing and/or merging it?

**Comment by ruimarinho** [comment]
Hi @msgilligan -- we could try but probably needs some rework on tag management for pushing the right image.

**Comment by msgilligan** [comment]
> Hi @msgilligan -- we could try but probably needs some rework on tag management for pushing the right image.

OK, I'll make an attempt at a pull-request and probably ignore the tag management issue in the first attempt -- I'll just focus on making sure it works correctly locally. Then we can discuss what to do about tags. Or do you already have an idea about tags?

**Comment by ruimarinho** [comment]
@msgilligan `v24.0.1` has been released via https://github.com/ruimarinho/docker-bitcoin-core/commit/6da5bc0ef21e98f9a5940329666a96f2209d8c7c.
