### ISSUE TITLE
Push 24.1 and 25.0 tags to docker hub

### ISSUE THREAD

**Issue by willcl-ark** [ruimarinho/docker-bitcoin-core#143]
Is there any chance we can have 24.1 and 25.0 pushed to dockerhub please?

**Comment by kroese** [comment]
I have them in my fork: https://github.com/dobtc/docker-bitcoin

**Comment by willcl-ark** [comment]
Thanks @kroese . I'll close this as I opened https://github.com/ruimarinho/docker-bitcoin-core/pull/144 to try and fix it here, too.
