### ISSUE TITLE
CLI commands not able to find RPC password

### ISSUE THREAD

**Issue by MidnightLightning** [ruimarinho/docker-bitcoin-core#43]
In starting up a Docker container with:

```
docker run --name bitcoin \
  -p 8332:8332 \
  -p 8333:8333 \
  ruimarinho/bitcoin-core:0.15.0.1 \
  -printtoconsole \
  -rpcpassword=foo \
  -rpcuser=bar
```

And then attempting to query it with `docker exec bitcoin bitcoin-cli getmininginfo`, I get an error message of: 

```
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/root/.bitcoin/bitcoin.conf)
```

That error seems to imply that it's looking for a `bitcoin.conf` file in `/root/.bitcoin/`, but the data directory is at `/home/bitcoin/.bitcoin/`.

How can I get this Docker container to properly start up and enable local RPC calls to be made?

**Comment by ruimarinho** [comment]
If you use a password for RPC calls, then you have to use on the cli command as well.

```sh
docker exec bitcoin bitcoin-cli -rpcuser=foo -rpcpassword=bar getmininginf
```

**Comment by ruimarinho** [comment]
@MidnightLightning for safety reasons, please read https://github.com/ruimarinho/docker-bitcoin-core/pull/44 carefully. TLDR; avoid `-rpcpassword` and use the newer `-rpcauth` option.

**Comment by MidnightLightning** [comment]
Ah, I was able to get the cookie authentication mode working; the key was simply to run the `bitcoin-cli` command as the same user the daemon was running under (`bitcoin`, not `root`):

```
docker run --name bitcoin \
  -p 8332:8332 \
  -p 8333:8333 \
  ruimarinho/bitcoin-core:0.15.0.1 \
  -printtoconsole
```

```
docker exec bitcoin --user bitcoin bitcoin-cli getmininginfo
```
