### ISSUE TITLE
Release new version to dockerhub

### ISSUE THREAD

**Issue by thomaseizinger** [ruimarinho/docker-bitcoin-core#59]
Unfortunately, the version on dockerhub does not have the latest changes (the exposed port). Could you release a new version so that the change is available?

**Comment by victorperin** [comment]
Right now, i'm doing it manually. If you want you can use my fork for now: https://hub.docker.com/r/victorperin/bitcoin-core/

**Comment by ruimarinho** [comment]
@victorperin @thomaseizinger will work on merging changes this week. Sorry about the delay.

**Comment by thomaseizinger** [comment]
@victorperin Thanks!
We went for creating our own image though because we needed it faster. What might be interesting though is that the whole Dockerfile can be much simpler because bitcoind is available in the alpine repository: https://github.com/coblox/docker-bitcoin-core/blob/master/Dockerfile

**Comment by victorperin** [comment]
No problem @ruimarinho it's normal to occur some delay sometimes.

About @thomaseizinger idea of simplifying the dokerfile, I don't agree, because repos could have some delay. (And also got the error below)

![image](https://user-images.githubusercontent.com/5847145/43687488-55625d8e-98ac-11e8-82b9-0ac8cf7593f6.png)

**Comment by thomaseizinger** [comment]
You have to use alpine v3.8! Then you can get the 0.16.1-r2 version. :)
Yes there might be some delay but in our case, we prefer an easier to
maintain Dockerfile over the latest patch release of bitcoin-core.

**Comment by ruimarinho** [comment]
It's currently building on Docker Hub. I agree with @victorperin — speed is the biggest differentiation. I'm glad alpine is shipping with an updated version nowadays.
