### ISSUE TITLE
Add environment variable for RPC calls

### ISSUE THREAD

**Issue by sancoder** [ruimarinho/docker-bitcoin-core#72]
In some environments like Synology docker is already integrated using good UI.
It might be easier for end user to specify RPCAUTH variable instead of dealing with command line.

**Comment by ruimarinho** [comment]
@sancoder totally understand. I think it would be a cool feature to translate command line arguments to variables, but usually it takes a bit of an effort. I'm open to merge this if you're willing to contribute some code with a PR, but right now I don't have enough time to work on this myself.

Hope you understand!
