### ISSUE TITLE
unable to copy bitcoin-0.18.1.tar.gz on mountpoints on base machine

### ISSUE THREAD

**Issue by abhyankar-amey** [ruimarinho/docker-bitcoin-core#83]
Hello,

I am trying to extract 'bitcoin-0.18.1.tar.gz' file at following path = /test/data1/abc dir
I am using 0.18 repo.
I have created this directory structure under 0.18 repo on my Ubuntu 18.04 laptop.
I get error saying file or directory not found.
My goal is to extract the tar file on persistent drive. (/test/data1/abc dir)

**Comment by ruimarinho** [comment]
Sorry, I do not understand your issue. Is it related to this docker image?

**Comment by abhyankar-amey** [comment]
I am using the Dockerfile from your repository.
But, I am trying to extract the downloaded tar.gz file on persistent external volumes on base machine.
As per your Dockerfile, it extract the contents of tar.gz file under /opt/bitcoin{version}

**Comment by ruimarinho** [comment]
That's just for temporary installing the daemon. You need to download from the website.
