### ISSUE TITLE
How to copy bitcoin.conf in external volume?

### ISSUE THREAD

**Issue by abhyankar-amey** [ruimarinho/docker-bitcoin-core#84]
Hello,

I want to copy bitcoin.conf on external volume i.e. /DataDrive/CoinData/Bitcoin directory.
How to do that?
/DataDrive/CoinData/Bitcoin is a directory structure on my base machine.

My docker-compose.yml file =  

bitcoind:
  image: btc-docker/bitcoin-core
  command:
    -printtoconsole
    -regtest=1
  volumes:
    - .DataDrive/CoinData/Bitcoin/bitcoin.conf:/DataDrive/CoinData/Bitcoin
    - .DataDrive/CoinClients/Bitcoin:/DataDrive/CoinClients/Bitcoin

**Comment by ruimarinho** [comment]
Mount your host directory on the `/home/bitcoin/` path as exemplified in the README. https://github.com/ruimarinho/docker-bitcoin-core#how-to-use-this-image

**Comment by abhyankar-amey** [comment]
But then, that way I can not follow my directory structure.
My requirement is to have 2 folders.
1 folder the data
Other folder contains client data.
I will be sending RCP calls from in house developed engine.
As of now I am achieving this from bitcoin-core GUI software in Ubuntu.
