### ISSUE TITLE
Impossible to use tag 0.18.1

### ISSUE THREAD

**Issue by straumat** [ruimarinho/docker-bitcoin-core#87]
In my docker-compose file i try to use : 
`image: ruimarinho/bitcoin-core:0.18.1`

and i get this error : `ERROR: manifest for ruimarinho/bitcoin-core:0.18.1 not found: manifest unknown: manifest unknown`

It works if i do `image: ruimarinho/bitcoin-core:0.16.3` for example

**Comment by ruimarinho** [comment]
Indeed @straumat! Docker Hub is not exactly the most reliable piece of software around.. :-) already triggered a rebuild. Thanks for alerting me.

Please re-open in case you don't see the tab in about two hours.
